Add magic_link example
Add the magic_link section to the config.example.toml section to prevent
this error when starting up the rfd-api service:

```
./target/release/rfd-api --config rfd-api/config.toml
Error: missing field `magic_link`
```

MagicLink was introduced in e8e3aae.