rfd-processor: Survive transient github errors (#499)
rfd-processor has recently crashed multiple times due to `401 Bad
credentials` from GitHub. This error was not caught and exits the
process.

```
Error: Scanner(GitHub(ClientError(HttpError { status: 401, ... "Bad credentials" ... })))
```
Perhaps caused by an expired App installation token (1hr expiration I
think).

This was compounded the systemd service missing a `Restart=always` -- so
a stray github error would cause rfd-processor to die.